language: python
python:
  - 2.7

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform



script: 
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_hasjob_b07943d5f6_4
  - python -m properform Push 47.88.50.110:15554 asdf_hasjob_b07943d5f6_4 ./profile_hasjob_b07943d5f6_4



 #2017-08-14 08:54:48 modified at 0 #2017-08-14 08:54:53 modified at 1 #2017-08-14 08:54:57 modified at 2 #2017-08-14 08:55:02 modified at 3 #2017-08-14 08:55:06 modified at 4