language: python
python:
  - 2.7

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform



script: 
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_hasjob_1fe4ce1e58_3
  - python -m properform Push 47.88.50.110:15554 asdf_hasjob_1fe4ce1e58_3 ./profile_hasjob_1fe4ce1e58_3



 #2017-08-14 10:25:44 modified at 0 #2017-08-14 10:25:48 modified at 1 #2017-08-14 10:25:53 modified at 2 #2017-08-14 10:25:57 modified at 3