language: python
python:
  - 2.7
cache:
  directories:
    - $HOME/.cache/pip
before_script:
  - psql -c 'create database hasjob_testing;' -U postgres

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - pip install -U pip wheel
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt
  - npm install casperjs
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

script:
  - nosetests -v tests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_hasjob_0974817fd0_3
  - python -m properform Push 47.88.50.110:15554 asdf_hasjob_0974817fd0_3 ./profile_hasjob_0974817fd0_3


addons:
  postgresql: "9.4"
services:
  - redis-server
 #2017-08-14 08:18:54 modified at 0 #2017-08-14 08:18:58 modified at 1 #2017-08-14 08:19:02 modified at 2 #2017-08-14 08:19:06 modified at 3