language: python
python:
  - 2.7

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


script:
  - nosetests --with-coverage --cover-package=admin,app,assets,forms,get-twitter,loghandler,models,search,twitter,uploads,utils,views,website --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_hasjob_fa4fce1b93_3
  - python -m properform Push 47.88.50.110:15554 asdf_hasjob_fa4fce1b93_3 ./profile_hasjob_fa4fce1b93_3




  #2017-08-14 10:27:16 modified at 0 #2017-08-14 10:27:21 modified at 1 #2017-08-14 10:27:25 modified at 2 #2017-08-14 10:27:29 modified at 3