language: python
python:
  - 2.7

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform



script: 
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_hasjob_df09e57ac7_4
  - python -m properform Push 47.88.50.110:15554 asdf_hasjob_df09e57ac7_4 ./profile_hasjob_df09e57ac7_4



 #2017-08-14 08:31:51 modified at 0 #2017-08-14 08:31:55 modified at 1 #2017-08-14 08:32:00 modified at 2 #2017-08-14 08:32:04 modified at 3 #2017-08-14 08:32:09 modified at 4