language: python
python:
  - 2.7

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform



script: 
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_hasjob_3c2f147044_4
  - python -m properform Push 47.88.50.110:15554 asdf_hasjob_3c2f147044_4 ./profile_hasjob_3c2f147044_4



 #2017-08-14 09:17:41 modified at 0 #2017-08-14 09:17:46 modified at 1 #2017-08-14 09:17:50 modified at 2 #2017-08-14 09:17:54 modified at 3 #2017-08-14 09:17:59 modified at 4