language: python
python:
  - 2.7

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform



script: 
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_hasjob_c40b1033b4_3
  - python -m properform Push 47.88.50.110:15554 asdf_hasjob_c40b1033b4_3 ./profile_hasjob_c40b1033b4_3



 #2017-08-14 09:14:19 modified at 0 #2017-08-14 09:14:23 modified at 1 #2017-08-14 09:14:28 modified at 2 #2017-08-14 09:14:32 modified at 3