language: python
python:
  - 2.7

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform



script: 
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_hasjob_43047b12eb_3
  - python -m properform Push 47.88.50.110:15554 asdf_hasjob_43047b12eb_3 ./profile_hasjob_43047b12eb_3



 #2017-08-14 10:21:37 modified at 0 #2017-08-14 10:21:41 modified at 1 #2017-08-14 10:21:46 modified at 2 #2017-08-14 10:21:50 modified at 3