language: python
python:
  - 2.7

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform



script: 
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_hasjob_b1915d281e_4
  - python -m properform Push 47.88.50.110:15554 asdf_hasjob_b1915d281e_4 ./profile_hasjob_b1915d281e_4



 #2017-08-14 09:59:55 modified at 0 #2017-08-14 10:00:00 modified at 1 #2017-08-14 10:00:04 modified at 2 #2017-08-14 10:00:09 modified at 3 #2017-08-14 10:00:13 modified at 4