language: python
python:
  - 2.7

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


script:
  - nosetests --with-coverage --cover-package=admin,app,assets,forms,get-twitter,loghandler,models,search,twitter,uploads,utils,views,website --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_hasjob_db94011993_4
  - python -m properform Push 47.88.50.110:15554 asdf_hasjob_db94011993_4 ./profile_hasjob_db94011993_4




  #2017-08-14 10:28:01 modified at 0 #2017-08-14 10:28:05 modified at 1 #2017-08-14 10:28:10 modified at 2 #2017-08-14 10:28:14 modified at 3 #2017-08-14 10:28:18 modified at 4